import { SlotTierId } from '@/types';

export type SlotSymbolId =
  | 'cherry'
  | 'bell'
  | 'seven'
  | 'bar'
  | 'gem'
  | 'ice7'
  | 'star'
  | 'cocktail'
  | 'cash_stack'
  | 'gold_watch'
  | 'yacht'
  | 'emerald_ring'
  | 'crown'
  | 'scepter'
  | 'throne'
  | 'faberge_egg'
  | 'planet'
  | 'atom'
  | 'robot'
  | 'infinity'
  | 'dragon'
  | 'coin'
  | 'lantern'
  | 'firecracker'
  | 'wild'
  | 'multiplier'
  | 'ultra';

export const SLOT_SYMBOL_ASSETS: Record<SlotTierId, Record<SlotSymbolId, string>> = {
  classic: {
    cherry: '/assets/slots/classic_1/classic_cherry.png',
    bell: '/assets/slots/classic_1/classic_bell.png',
    seven: '/assets/slots/classic_1/classic_7.png',
    bar: '/assets/slots/classic_1/classic_bar.png',
    gem: '',
    ice7: '',
    star: '',
    cocktail: '',
    cash_stack: '',
    gold_watch: '',
    yacht: '',
    emerald_ring: '',
    crown: '',
    scepter: '',
    throne: '',
    faberge_egg: '',
    planet: '',
    atom: '',
    robot: '',
    infinity: '',
    dragon: '',
    coin: '',
    lantern: '',
    firecracker: '',
    wild: '/assets/slots/classic_1/classic_wild.png',
    multiplier: '/assets/slots/classic_1/classic_multiplier.png',
    ultra: '/assets/slots/classic_1/classic_ultra.png',
  },
  sapphire: {
    cherry: '',
    bell: '',
    seven: '',
    bar: '',
    gem: '/assets/slots/sapphire_2/sapphire_Gem.png',
    ice7: '/assets/slots/sapphire_2/sapphire_ice7.png',
    star: '/assets/slots/sapphire_2/sapphire_star.png',
    cocktail: '/assets/slots/sapphire_2/sapphire_cocktail.png',
    cash_stack: '',
    gold_watch: '',
    yacht: '',
    emerald_ring: '',
    crown: '',
    scepter: '',
    throne: '',
    faberge_egg: '',
    planet: '',
    atom: '',
    robot: '',
    infinity: '',
    dragon: '',
    coin: '',
    lantern: '',
    firecracker: '',
    wild: '/assets/slots/sapphire_2/sapphire_wild.png',
    multiplier: '/assets/slots/sapphire_2/sapphire_multiplier.png',
    ultra: '/assets/slots/sapphire_2/sapphire_ultra.png',
  },
  emerald: {
    cherry: '',
    bell: '',
    seven: '',
    bar: '',
    gem: '',
    ice7: '',
    star: '',
    cocktail: '',
    cash_stack: '/assets/slots/emerald_3/emerald_cash_stack.png',
    gold_watch: '/assets/slots/emerald_3/emerald_gold_watch.png',
    yacht: '/assets/slots/emerald_3/emerald_yacht.png',
    emerald_ring: '/assets/slots/emerald_3/emerald_ring.png',
    crown: '',
    scepter: '',
    throne: '',
    faberge_egg: '',
    planet: '',
    atom: '',
    robot: '',
    infinity: '',
    dragon: '',
    coin: '',
    lantern: '',
    firecracker: '',
    wild: '/assets/slots/emerald_3/emerald_wild.png',
    multiplier: '/assets/slots/emerald_3/emerald_multiplier.png',
    ultra: '/assets/slots/emerald_3/emerald_ultra.png',
  },
  royal: {
    cherry: '',
    bell: '',
    seven: '',
    bar: '',
    gem: '',
    ice7: '',
    star: '',
    cocktail: '',
    cash_stack: '',
    gold_watch: '',
    yacht: '',
    emerald_ring: '',
    crown: '/assets/slots/royal_4/royal_crown.png',
    scepter: '/assets/slots/royal_4/royal_scepter.png',
    throne: '/assets/slots/royal_4/royal_throne.png',
    faberge_egg: '/assets/slots/royal_4/royal_faberge_egg.png',
    planet: '',
    atom: '',
    robot: '',
    infinity: '',
    dragon: '',
    coin: '',
    lantern: '',
    firecracker: '',
    wild: '/assets/slots/royal_4/royal_wild.png',
    multiplier: '',
    ultra: '/assets/slots/royal_4/royal_ultra.png',
  },
  celestial: {
    cherry: '',
    bell: '',
    seven: '',
    bar: '',
    gem: '',
    ice7: '',
    star: '',
    cocktail: '',
    cash_stack: '',
    gold_watch: '',
    yacht: '',
    emerald_ring: '',
    crown: '',
    scepter: '',
    throne: '',
    faberge_egg: '',
    planet: '/assets/slots/celestial_5/celestial_planet.png',
    atom: '/assets/slots/celestial_5/celestial_atom.png',
    robot: '/assets/slots/celestial_5/celestial_robot.png',
    infinity: '/assets/slots/celestial_5/celestial_infinity.png',
    dragon: '',
    coin: '',
    lantern: '',
    firecracker: '',
    wild: '/assets/slots/celestial_5/celestial_wild.png',
    multiplier: '/assets/slots/celestial_5/celestial_multiplier.png',
    ultra: '/assets/slots/celestial_5/celestial_ultra.png',
  },
  dragonEvent: {
    cherry: '',
    bell: '',
    seven: '',
    bar: '',
    gem: '',
    ice7: '',
    star: '',
    cocktail: '',
    cash_stack: '',
    gold_watch: '',
    yacht: '',
    emerald_ring: '',
    crown: '',
    scepter: '',
    throne: '',
    faberge_egg: '',
    planet: '',
    atom: '',
    robot: '',
    infinity: '',
    dragon: '/assets/slots/event_dragon_6/dragon_dragon.png',
    coin: '/assets/slots/event_dragon_6/dragon_coin.png',
    lantern: '/assets/slots/event_dragon_6/dragon_lantern.png',
    firecracker: '/assets/slots/event_dragon_6/dragon_firecrackers.png',
    wild: '/assets/slots/event_dragon_6/dragon_wild.png',
    multiplier: '/assets/slots/event_dragon_6/dragon_multiplier.png',
    ultra: '/assets/slots/event_dragon_6/dragon_ultra.png',
  },
};

export const FEATURE_GLOBAL_ASSETS = {
  scatter: '/assets/slots/scatter_galaxy_chip.png',
  bonus: '/assets/slots/bonus_vault_door.png',
  jackpot: '/assets/slots/jackpot.png',
};
